export const dates = [
     {
          date: '2023-12-03',
          pay: false,
          show: false,
          weekend: true,
          addText: {
               text: '',
               category: '',
          },
          everyDay: false,
          description: {
               desPay: '',
               desShow: '',
          },
          dateCategory: '',
     },
     {
          date: '2023-12-04',
          pay: true,
          show: true,
          weekend: false,
          addText: {
               text: '(за исключением нерезидентов)',
               category: 'pay',
          },
          everyDay: false,
          description: {
               desPay: 'Налог на доходы иностранных организаций, не осуществляющих деятельность в Республике Беларусь через постоянное представительство',
               desShow: 'Утилизационный сбор',
          },
          dateCategory: 'calendarOrg',
     },
     {
          date: '2023-12-28',
          pay: true,
          show: true,
          weekend: false,
          addText: {
               text: '(за исключением нерезидентов)',
               category: 'pay',
          },
          everyDay: false,
          description: {
               desPay: 'На доходы налог иностранных организаций, не осуществляющих деятельность в Республике Беларусь через постоянное представительство',
               desShow: 'Утилизационный сбор',
          },
          dateCategory: 'calendarOrg',
     },
     {
          date: '2023-12-15',
          pay: true,
          show: true,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: true,
          description: {
               desPay: 'Оффшорный сбор',
               desShow: 'НДС',
          },
          dateCategory: 'calendarOrg',
     },
     {
          date: '2023-12-25',
          pay: true,
          show: true,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: false,
          description: {
               desPay: 'Оффшорный сбор',
               desShow: 'НДС',
          },
          dateCategory: 'calendarOrg',
     },
     {
          date: '2024-01-10',
          pay: false,
          show: true,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: false,
          description: {
               desPay: '',
               desShow: 'Текст',
          },
          dateCategory: 'calendarOrg',
     },
     {
          date: '2023-12-12',
          pay: true,
          show: false,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: false,
          description: {
               desPay: 'Утилизационный сбор',
               desShow: '',
          },
          dateCategory: 'calendarOrg',
     },
     {
          date: '2024-01-25',
          pay: true,
          show: false,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: false,
          description: {
               desPay: 'Утилизационный сбор',
               desShow: '',
          },
          dateCategory: 'calendarOrg',
     },
     {
          date: '2023-12-06',
          pay: true,
          show: true,
          weekend: false,
          addText: {
               text: '(за исключением нерезидентов)',
               category: 'pay',
          },
          everyDay: false,
          description: {
               desPay: 'Налог на прибыль',
               desShow: 'Утилизационный сбор',
          },
          dateCategory: 'calendarIP',
     },
     {
          date: '2023-12-05',
          pay: false,
          show: true,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: true,
          description: {
               desPay: '',
               desShow: 'Оффшорный сбор',
          },
          dateCategory: 'calendarIP',
     },
     {
          date: '2024-01-10',
          pay: true,
          show: false,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: false,
          description: {
               desPay: 'Акцизный сбор',
               desShow: '',
          },
          dateCategory: 'calendarIP',
     },
     {
          date: '2023-12-14',
          pay: true,
          show: true,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: false,
          description: {
               desPay: 'Налог на имущество организаций',
               desShow: 'Акцизный сбор',
          },
          dateCategory: 'calendarIP',
     },
     {
          date: '2023-12-20',
          pay: true,
          show: false,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: true,
          description: {
               desPay: 'Утилизационный сбор',
               desShow: '',
          },
          dateCategory: 'calendarIP',
     },
     {
          date: '2024-01-25',
          pay: false,
          show: true,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: true,
          description: {
               desPay: '',
               desShow: 'Налог на добавленную стоимость',
          },
          dateCategory: 'calendarIP',
     },
     {
          date: '2023-12-30',
          pay: false,
          show: true,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: true,
          description: {
               desPay: '',
               desShow: 'Утилизационный сбор',
          },
          dateCategory: 'calendarIP',
     },
     {
          date: '2023-12-05',
          pay: true,
          show: true,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: false,
          description: {
               desPay: 'Налог на доходы иностранных организаций',
               desShow: 'Акцизный сбор',
          },
          dateCategory: 'calendarIP',
     },
     {
          date: '2024-01-10',
          pay: true,
          show: false,
          weekend: false,
          addText: {
               text: '',
               category: '',
          },
          everyDay: true,
          description: {
               desPay: 'Оффшорный сбор',
               desShow: '',
          },
          dateCategory: 'calendarIP',
     },
];